.\"	$OpenBSD$
.\"
.\" Copyright (c) 2025 Jan Klemkow <j.klemkow@wemelug.de>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt LIBCERT 3
.Os
.Sh NAME
.Nm cert_load_issuer_key ,
.Nm cert_load_subject_key
.Nd certificate library
.Sh SYNOPSIS
.In cert.h
.Ft int
.Fn cert_load_issuer_key "struct cert *cert" "const char *path"
.Ft int
.Fn cert_load_subject_key "struct cert *cert" "const char *path"
.Sh DESCRIPTION
The functions
.Fn cert_load_issuer_key
and
.Fn cert_load_subject_key
load the keys for issuer und subject of the certificate from PEM files in
.Ar path .
.Pp
By default a subject key is generated if its not given via
.Fn cert_load_subject_key .
When an issuer key is not given via
.Fn cert_load_issuer_key
the subject key is also used the issuer key.
.Sh RETURN VALUES
The functions
.Fn cert_load_issuer_key
and
.Fn cert_load_subject_key
return 1 on success and 0 on error.
.Sh SEE ALSO
.Xr cert_new 3
.Sh STANDARDS
.%R RFC 5280
.Sh AUTHORS
.An Jan Klemkow Aq Mt j.klemkow@wemelug.de
