.\"	$OpenBSD$
.\"
.\" Copyright (c) 2025 Jan Klemkow <j.klemkow@wemelug.de>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt LIBCERT 3
.Os
.Sh NAME
.Nm cert_config_add_crl_ur ,
.Nm cert_config_set_cps ,
.Nm cert_config_authority_info_access
.Nd certificate type
.Sh SYNOPSIS
.In cert.h
.Ft int
.Fn cert_config_add_crl_uri "struct cert_config *config" "const char *url"
.Ft void
.Fn cert_config_set_cps "struct cert_config *config" "const char *cps"
.Ft void
.Fn cert_config_authority_info_access "struct cert_config *config" "const char *aia"
.Sh DESCRIPTION
The
.Fn cert_config_add_crl_uri
functions add
.Ar url
string to the revocation list of the certificate.
.Pp
The
.Fn cert_config_set_cps
function sets the certificate policy URI to
.Ar cps .
.Pp
The
.Fn cert_config_authority_info_access
functions sets authority information access to
.Ar aia .
.Sh RETURN VALUES
.Fn cert_config_add_crl_uri
returns 1 on success and 0 on failure.
.Sh SEE ALSO
.Xr cert_config_new 3
.Sh STANDARDS
.%R RFC 5280
.Sh AUTHORS
.An Jan Klemkow Aq Mt j.klemkow@wemelug.de
